/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'james' at '11/13/15 8:39 AM' with Gradle 2.6
 *
 * @author james, @date 11/13/15 8:39 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
