/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'james' at '11/12/15 2:41 PM' with Gradle 2.6
 *
 * @author james, @date 11/12/15 2:41 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
