/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'james' at '10/23/15 6:56 AM' with Gradle 2.6
 *
 * @author james, @date 10/23/15 6:56 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
