/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'james' at '9/9/15 2:27 PM' with Gradle 2.5
 *
 * @author james, @date 9/9/15 2:27 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
