/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'james' at '9/28/15 11:52 AM' with Gradle 2.6
 *
 * @author james, @date 9/28/15 11:52 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
