/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'james' at '9/4/15 1:20 PM' with Gradle 2.5
 *
 * @author james, @date 9/4/15 1:20 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
